---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openstack-tenant-exporter.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "openstack-tenant-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    port: metrics
    path: /metrics
  jobLabel: jobLabel
  namespaceSelector:
    any: true
  selector:
    matchLabels:
{{- include "openstack-tenant-exporter.labels" . | nindent 6 }}
