{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.secret.cloudConfig }}
{{- end }}
