{
 "title": "OpenStack Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_total_instances_used", "legendFormat": "total_instances_used" },
    {
     "expr": "openstack_max_total_instances != -1",
     "legendFormat": "max_total_instances"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_total_cores_used", "legendFormat": "total_cores_used" },
    {
     "expr": "openstack_max_total_cores != -1",
     "legendFormat": "max_total_cores"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_total_ram_used", "legendFormat": "total_ram_used" },
    { "expr": "openstack_max_total_ram != -1", "legendFormat": "max_total_ram" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Volumes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_total_volumes_used", "legendFormat": "total_volumes_used" },
    {
     "expr": "openstack_max_total_volumes != -1",
     "legendFormat": "max_total_volumes"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_total_snapshots_used", "legendFormat": "total_snapshots_used" },
    {
     "expr": "openstack_max_total_snapshots != -1",
     "legendFormat": "max_total_snapshots"
    }
   ]
  },
  {
   "title": "Volumes Storage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_total_volume_gigabytes_used",
     "legendFormat": "total_volume_gigabytes_used"
    },
    {
     "expr": "openstack_max_total_volume_gigabytes != -1",
     "legendFormat": "max_total_volume_gigabytes"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Floating IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_total_floatingips_used",
     "legendFormat": "total_floatingips_used"
    },
    {
     "expr": "openstack_max_floatingips != -1",
     "legendFormat": "max_floatingips"
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_total_loadbalancers_used",
     "legendFormat": "total_loadbalancers_used"
    },
    {
     "expr": "openstack_max_loadbalancers != -1",
     "legendFormat": "max_loadbalancers"
    }
   ]
  }
 ]
}